### ISSUE TITLE
ussr in 2015?

### ISSUE THREAD

**Issue by mister-elliott** [owid/co2-data#10]
continents.csv
.....
USSR,,2015,Europe (excl. EU-28)
USSR,,2015,Europe (excl. EU-28)

there is no ussr in 2015, but maybe one of these should be excl. EU-27??

**Comment by edomt** [comment]
@bnjmacdonald Most likely there's no actual issue here—the Year column is probably set to `2015` for all rows, but not used at all, so it just needs removing.

**Comment by mister-elliott** [comment]
lots of nations are shown as (excl. EU-27) and (excl. EU-28), so one would think that USSR  for consistency should be listed that way (though, most of the USSR is in Asia so it is a bit weird to show it as Europe).
for example:
Albania,ALB,2015,Europe
Albania,,2015,Europe (excl. EU-28)
Albania,,2015,Europe (excl. EU-27)

**Comment by edomt** [comment]
Fixed in c3b762dac1ac670ddd39bdeb1c00e3a0f162df85
