### ISSUE TITLE
gdp data question

### ISSUE THREAD

**Issue by cortinah** [owid/co2-data#12]
Thank you for this resource.

The codebook indicates that the gdp data is: Total real gross domestic product, inflation-adjusted. 

But it is not clear if the gdp data is in the same currency and different countries can be added.  Could you please clarify if all the gdp data is in same currency (as well base year)?

Also, the latest GDP data is from 2016. Would it be possible to get a more recent update?

thank you

**Comment by edomt** [comment]
Hi @cortinah 

The full definition for `gdp` is "GDP adjusted for price changes over time (inflation) and price differences between countries – it is measured in international-$ in 2011 prices."
We've updated the codebook to clarify this.

We'll be working this summer to update this dataset, including with the latest GDP data.
