### ISSUE TITLE
Update Global Carbon Project to 2020 data

### ISSUE THREAD

**Issue by edomt** [owid/co2-data#13]
The Global Carbon Project released in late 2020 a new update of their data, used in this repo as [`co2-data/scripts/input/co2/co2_gcp.xlsx`](https://github.com/owid/co2-data/blob/master/scripts/input/co2/co2_gcp.xlsx)

- [Landing page](https://www.icos-cp.eu/science-and-impact/global-carbon-budget/2020)
- [Direct link](https://data.icos-cp.eu/licence_accept?ids=%5B%22xUUehljs1oTazlGlmigAhvfe%22%5D)

Our input should be updated to the 2020 version, and the pipeline should be re-run.

**Comment by HannahRitchie** [comment]
We have actually already run this update. It extended our time-series from 2018 to 2019. In every annual update, the latest year's figures (i.e. 2020) are preliminary (and marked differently from the rest of the data). So I deliberately did not take the 2020 figures in this update.
