### ISSUE TITLE
GHG update from CAIT

### ISSUE THREAD

**Issue by davidmihalyi** [owid/co2-data#20]
Dear OWD team,

The CAIT has data until 2018. Would it be possible to update the GHG total (total_ghg, ghg_per_capita) values? Current OWD dataset only goes until 2016.

Thanks

**Comment by bnjmacdonald** [comment]
Thanks for bringing this up, we will look into this as soon as we can

**Comment by davidmihalyi** [comment]
Great, looking forward to it.

**Comment by pabloarosado** [comment]
CAIT data has been updated.
