### ISSUE TITLE
Please add Land-use co2 emissions file from OWID to repository 

### ISSUE THREAD

**Issue by cortinah** [owid/co2-data#26]
Hello, related to https://github.com/owid/co2-data/issues/25#issue-1202648526

Could you please kindly add the separate file: global-co2-fossil-plus-land-use.csv from:
https://ourworldindata.org/co2-emissions to this repository?

This would enable the file to be called from code and tracked.   Thanks in advance, I hope this addresses your helpful comment.

![image](https://user-images.githubusercontent.com/22863380/163514713-66c74d7e-2d48-4ba4-9024-58e1ab0db554.png)

**Comment by pabloarosado** [comment]
Hi @cortinah , thanks for your suggestion. For the time being that dataset is hosted [here](https://github.com/owid/owid-datasets/tree/master/datasets/Global%20Carbon%20Budget%20(GCP%2C%202021)). So, if you want to have a link to the csv file directly, you can use [this link to the raw file](https://github.com/owid/owid-datasets/raw/master/datasets/Global%20Carbon%20Budget%20(GCP%2C%202021)/Global%20Carbon%20Budget%20(GCP%2C%202021).csv).
We are currently working on a better way to access datasets.
