### ISSUE TITLE
Negative co2 emission values

### ISSUE THREAD

**Issue by Symphonew** [owid/co2-data#5]
The current database contains some negative values in the co2 column, which cannot be correct in my understanding. 
See the following query (written in R):
> library(dplyr)
> OWID.CO2 = read.csv("https://github.com/owid/co2-data/raw/master/owid-co2-data.csv")
> df = OWID.CO2 %>% subset(co2<0) %>% select(iso_code, country, year, co2)
> df
      iso_code      country year    co2
10621      IRQ         Iraq 1948 -0.095
11681      KWT       Kuwait 1952 -0.436
11682      KWT       Kuwait 1953 -0.051
18235      SAU Saudi Arabia 1951 -0.348
18236      SAU Saudi Arabia 1952 -0.172
18314      SEN      Senegal 1968 -0.081
22945      VEN    Venezuela 1930 -1.165
22946      VEN    Venezuela 1931 -0.256

**Comment by edomt** [comment]
Thank you @Symphonew, we'll look into this.

**Comment by edomt** [comment]
Fixed in 4ffb1540753164208df140d437f9d4bad73526b9
