### ISSUE TITLE
Eswatini doesn't have co2 per capita data

### ISSUE THREAD

**Issue by Alastair-L** [owid/co2-data#6]
Not sure if there's a good reason for this, but it appears that Eswatini has data for both co2 and population, but not co2 per capita? Is this as simple as a division? (looks like it happens here: https://github.com/owid/co2-data/blob/master/scripts/co2_emissions.py#L230-L234)
The same omissions are in the csv and xlsx files
![image](https://user-images.githubusercontent.com/32168886/117562064-685c3100-b0df-11eb-9927-de8be90cd553.png)
Edit: co2 per gdp is also missing

**Comment by edomt** [comment]
Fixed in 4ffb1540753164208df140d437f9d4bad73526b9

**Comment by Alastair-L** [comment]
Thanks mate!
