### ISSUE TITLE
population for north america is wrong

### ISSUE THREAD

**Issue by mister-elliott** [owid/co2-data#9]
population.csv:
...
North America,2019,366600992
...

that is roughly the population of the USA and Canada.  North America is a lot more countries than that

**Comment by edomt** [comment]
ad206e8 fixes the issue in the population file, but the whole pipeline will need to be rerun to fix per-capita values.

**Comment by edomt** [comment]
Fixed in 4ffb1540753164208df140d437f9d4bad73526b9
